carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('decrement_item_count/<int:product_id>/<int:cart_item_id>/', views.decrement_item_count, name='decrement_item_count'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    
    path('my_secure_admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # Orders URL
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name='store'),
    
    # adding 'category/' to urls so that we can have 'search/' endpoint seperately 
    # otherwise, we need to tweak for the 'search/' endpoint
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),

    path('search/', views.search, name='search'),

    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

carts/models.py
from django.db import models
from store.models import Product, ProductVariation
from accounts.models import Account

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.cart_id
    
class CartItem(models.Model):
    # to assigning the user after uer login
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # as many products can have same variation and same product can have various variations
    product_variations = models.ManyToManyField(ProductVariation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    # this calculates the subtotal price for each cart items
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self) -> str:
        return self.product.name

store/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Avg, Count

from category.models import Category
from accounts.models import Account, UserProfile

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_details', args=[self.category.slug, self.slug])
    
    def average_rating(self):
        # filtering the reviewws of the particular product and finding the average of 'ratings' field and 
        # storing average in a key named 'average
        rating = ReviewRatings.objects.filter(product=self, status=True).aggregate(average=Avg('ratings'))
        
        # if product does not have any review then
        if rating['average'] is None:
            # return 0
            return 0
        
        # if product has any review then the average of reviews is returned
        return rating['average']
    
    def count_rating(self):
        # filtering the reviewws of the particular product and finding the count of 'ratings' field and 
        # storing average in a key named 'count
        rating = ReviewRatings.objects.filter(product=self, status=True).aggregate(count=Count('ratings'))

        # if product does not have any review then
        if rating['count'] is None:
            # return 0
            return 0
        
        # if product has any review then the count of reviews is returned
        return rating['count']

    def __str__(self) -> str:
        return self.name
    

# Custom PRoduct Variation Manager
class ProductVariationManager(models.Manager):  # inherits from models.Manager, which is the base class for Django's model managers.
    # override the default query behavior by calling super().filter() to apply custom filters based on the variation_category and is_active fields.
    def colors(self):
        return super().filter(variation_category='color', is_active=True)
    
    # override the default query behavior by calling super().filter() to apply custom filters based on the variation_category and is_active fields.
    def sizes(self):
        return super().filter(variation_category='size', is_active=True)
    


product_variation_category_choices = (
    ('color', 'Color'),
    ('size', 'Size'),
)


class ProductVariation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=50, choices=product_variation_category_choices)
    variation_value = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # Custom Manager is assigned to the objects attribute, which means any query on ProductVariation.objects will use ProductVariationManager's methods, not the default methods. 
    # So, essentially extending the model's functionality with custom query methods, improving code reusability and readability.
    objects = ProductVariationManager()

    def __str__(self):
        return self.variation_value
    
class ReviewRatings(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(blank=True)
    ratings = models.FloatField()
    ip = models.CharField(max_length=10, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Review Rating"
        verbose_name_plural = "Review Ratings"

    def __str__(self):
        return self.subject
    
    def review_first_10_words(self):
        # Split the content into words and join the first 10
        return ' '.join(self.review.split()[:10]) + '...'



class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Product_Gallery')

    def __str__(self):
        return self.product.name
    
    class Meta:
        verbose_name_plural = 'Product Gallery'

store/forms.py
from django import forms

from .models import ReviewRatings

class ReviewRatingsForm(forms.ModelForm):
    class Meta:
        model = ReviewRatings
        fields = ['subject', 'review', 'ratings']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Cart, CartItem
from store.models import Product, ProductVariation

# Create your views here.
def _get_cart_id(request):
    # getting the from session_key
    cart = request.session.session_key

    # if there is no session_key exists then create one
    if not cart:
        # creating a new session
        cart = request.session.create()

    # returning the cart
    return cart

def cart(request):
    total = 0
    cart_items = None
    try:
        # if authenticated user i.e., user logs in then fetch cart items depending on the user
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user)

        # if user not logs in then fetch cart items depending on the session id from request
        else:
            # getting the cart and cart items from session id
            cart = Cart.objects.get(cart_id = _get_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart)
        # iterating over cart items
        for cartitem in cart_items:
            total += cartitem.product.price * cartitem.quantity

    # if cartitem does not present
    except Cart.DoesNotExist:
        # do nothing and use the predefined values 0 and None
        pass
    
    tax = total * 0.02
    grand_total = total + tax

    context = {
        'cart_items': cart_items,
        'total': total,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/cart.html', context)

# creating a private function to get the cart_id. Here _ means private function

def add_to_cart(request, product_id):   # passing product_id from product_details.html page
    # getting the current logged in user
    current_user = request.user

    # fetching the product
    product = Product.objects.get(id=product_id)

    # for storing product variations for a particular product
    product_variation = []

    if request.method == 'POST':
        # taking all key and value pair as if in future we introduce brand or any other variation, 
        # then also our code will work
        for key, value in request.POST.items():
            # checking if the key and value matches with the variation_catogory and variation_value of ProductVariation model
            try:
                variation = ProductVariation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)

            # if key and value doesnot match like csrfmiddlewaretoken, then do nothing and just skip
            except:
                pass
        
    # if user not logged in then getting the cart_id from the session else create cart
    if not current_user.is_authenticated:
        # getting the cart, if not then create cart
        try:
            # getting the cart object
            cart = Cart.objects.get(cart_id=_get_cart_id(request))

        # if cart is not present
        except Cart.DoesNotExist:
            # creating a new cart object
            cart = Cart.objects.create(
                cart_id = _get_cart_id(request)
            )
            cart.save()

    # if logged in user then getting the cart_items using the user
    if current_user.is_authenticated:
        cart_items = CartItem.objects.filter(product=product, user=current_user)

    # if not logged in user then getting the cart_items using the cart id
    else:
        # Getting all cart items from cart depending on product
        cart_items = CartItem.objects.filter(product=product, cart=cart)

    # Checking for existance of the cart item
    is_cart_item_exists = cart_items.exists()

    # if cart item already exists in the cart
    if is_cart_item_exists:
        # for storing existing variations of cart items
        existing_variation_list = []
        # for storing the id of the existing variation in the existing_variation_list
        cart_item_id = []

        # looping over the cart items
        for item in cart_items:
            # getting all variations for a particular item in cart item
            existing_variation = item.product_variations.all()

            # appending existing_variation to existing_variation_list after converting queryset to a list
            existing_variation_list.append(list(existing_variation))

            # storing id of the particular cart item
            cart_item_id.append(item.id)


        # checking if the current product variation is in the exisitng product variation list
        if product_variation in existing_variation_list:
            # getting the iindex of the current variation from the existing variation list
            index = existing_variation_list.index(product_variation)

            # getting the id
            item_id = cart_item_id[index]

            # getting the cart item
            cart_item = CartItem.objects.get(product=product, id=item_id)

            # increasing the quantity of the particular variation
            cart_item.quantity += 1

            # saving the cart item
            cart_item.save()

        # if the current product variation is not in the existing product variation list
        else:
            # if user is logged in then creating the cart item using the user
            if current_user.is_authenticated:
                # creating a new cart item
                cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)

            # if user is not logged in then creating the cart item using the cart id
            else:
                # creating a new cart item
                cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)

            # if we have an variation of product
            if product_variation:
                # clear previous variation from cart item
                cart_item.product_variations.clear()
                
                # adding new variation to cart item
                cart_item.product_variations.add(*product_variation) # unpacking existing variation
            
            # saving the cart item
            cart_item.save()

    # if cart item does not exists in the cart
    else:
        # if user logged in then create using the user
        if current_user.is_authenticated:
            # creating cartitem object with quantity 1
            cart_item = CartItem.objects.create(
                product=product,
                user=current_user,
                quantity=1,
            )
        # if user is not logged in then create using the cart id
        else:
            # creating cartitem object with quantity 1
            cart_item = CartItem.objects.create(
                product=product,
                cart=cart,
                quantity=1,
            )

        # if we have an variation of product
        if product_variation:
            # clear previous variation from cart item
            cart_item.product_variations.clear()
            
            # adding new variation to cart item
            cart_item.product_variations.add(*product_variation) # unpacking existing variation
        
    # saving the cartitem
    cart_item.save()

    # taking the customer to the cart page
    return redirect('cart')

# implement minus button functionality  to decrement product quantity in cart page
def decrement_item_count(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)

    # if found cart_item with the cart, product and id then decrement ite's count by 1
    try:
        # if user logged in then get the cart item using the user
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(user=request.user, product=product, id=cart_item_id)

        # if the user is not logged in then get the cart item using the cart
        else:
            cart = Cart.objects.get(cart_id=_get_cart_id(request))
            cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)

        # if quantity is more than 1, decrement the qunatity by 1
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()

        # if quantity is only 1, delete the cart item
        else:
            cart_item.delete()

    # if not found cart_item with the cart, product and id then do nothing
    except:
        pass

    return redirect('cart')

def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)

    # if logged in user then getting the cart item using the user
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(user=request.user, product=product, id=cart_item_id)

    # if no loggd in then getting the cart item using the cart from session
    else:
        cart = Cart.objects.get(cart_id=_get_cart_id(request))
        cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)

    # deleting the item
    cart_item.delete()

    return redirect('cart')


@login_required(login_url='login')
def checkout(request):
    # code copied from cart view
    total = 0
    cart_items = None
    try:
        # if user is logged in
        if request.user.is_authenticated:
            # getting the cart using the user
            cart_items = CartItem.objects.filter(user=request.user)

        # if user is not logged in
        else:
            # getting the cart items using cart id from session
            cart = Cart.objects.get(cart_id = _get_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart)
            
        # iterating over cart items
        for cartitem in cart_items:
            total += cartitem.product.price * cartitem.quantity

    # if cartitem does not present
    except Cart.DoesNotExist:
        # do nothing and use the predefined values 0 and None

templates/store/product_details.html
{% extends 'base.html' %}
<!-- loading static files -->
{% load static %}

<!-- Main content -->
{% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <!-- Giving custom class name mainImage for styling with CSS and running JQuery script -->
            <div class="img-big-wrap mainImage">
              <!-- Centering the image on the main image display box -->
              <center>
                <img src="{{ product.images.url }}" />
              </center>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <!-- gallery-wrap .end// -->
           <ul class="thumb">
            <li>
              <!-- For having the primary image in the image thumbnail list  -->
              <a href="{{ product.images.url }}">
                <img src="{{ product.images.url }}" alt="{{ product.name }} image">
              </a>
              <!-- looping over all the product images in product gallery -->
              {% for product_image in product_gallery %}
                <a href="{{ product_image.image.url }}">
                  <img src="{{ product_image.image.url }}" alt="{{ product_image.product.name }} image">
                </a>
              {% endfor %}
            </li>
           </ul>
        </aside>
        <main class="col-md-6 border-left">
          <!-- Implementing form to submit the product with variation -->
          <form action="{% url 'add_to_cart' product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{ product.name }}</h2>
              
              <!-- Showing average raing and total number of rating for this product -->
              <div class="rating-stars">
                <span>
                  {# fa-star-o means blank star, fa-star-half-o means half star, fa-star means full star #}
                  <i class="fa fa-star{% if product.average_rating < 0.5 %}-o{% elif product.average_rating < 1 %}-half-o {% endif %}"></i>
                  <i class="fa fa-star{% if product.average_rating < 1.5 %}-o{% elif product.average_rating < 2 %}-half-o {% endif %}"></i>
                  <i class="fa fa-star{% if product.average_rating < 2.5 %}-o{% elif product.average_rating < 3 %}-half-o {% endif %}"></i>
                  <i class="fa fa-star{% if product.average_rating < 3.5 %}-o{% elif product.average_rating < 4 %}-half-o {% endif %}"></i>
                  <i class="fa fa-star{% if product.average_rating < 4.5 %}-o{% elif product.average_rating < 5 %}-half-o {% endif %}"></i>
                </span>
                <span>Total {{ product.count_rating }} reviews</span>
              </div>

              <div class="mb-3">
                <var class="price h4">$ {{ product.price }}</var>
              </div>

              <p>{{ product.description }}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <div
                    class="btn-group btn-group-sm btn-group-toggle flex-wrap"
                    data-toggle="buttons"
                  >
                    {# As we have a foreignkey relationship from product to productvariation, as we haven't set related name, #}
                    {# so,to access the productvariation table from the product table attribute, #}
                    {# we need to use '_set' at the end of productvariation and #}
                    {# then we can access the attributes and functions of productvariation table with product class object. #}
                    <!-- RADIO options for colors -->
                    {% for color in product.productvariation_set.colors %}
                    <label class="btn btn-light">
                      <input
                        type="radio"
                        name="color"
                        value="{{ color.variation_value | capfirst }}"
                      />
                      {# here, color is a queryset, so from queryset we are taking variation_value field #}
                      <!-- capfirst converts first letter to capital and rest in small -->
                      {{ color.variation_value | capfirst}}
                    </label>
                    {% endfor %}
                  </div>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <div
                    class="btn-group btn-group-sm btn-group-toggle flex-wrap"
                    data-toggle="buttons"
                  >
                    {% for size in product.productvariation_set.sizes %}
                    <label class="btn btn-light">
                      <input
                        type="radio"
                        name="size"
                        value="{{ size.variation_value | capfirst }}"
                      />
                      {{ size.variation_value | capfirst }}
                    </label>
                    {% endfor %}
                  </div>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if product.stock <= 0 %}
                <h5 class="text-danger">Out of stock</h5>
              {% else %}
              <!-- if the product has more than 0 stock -->
              <button type="submit" class="btn btn-primary">
                <span class="text"
                  >Add to cart <i class="fas fa-shopping-cart"></i
                ></span>
              </button>
              <!-- end if -->
              {% endif %}
            </article>
            <!-- product-info-aside .// -->
          </form>
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        <header class="section-heading">
          <h5>Give your valuable review about {{ product.name }} </h5>
        </header>
        <article class="box mb-3">
          {% include 'includes/alerts.html' %}
          <form action="{% url 'submit_review' product.id %}" method="POST">
            {% csrf_token %}

            <!-- Review Stars -->
            <div class="mb-3 row">
              <label for="subject" class="col-sm-2 col-form-label">Rate this product</label>
              <div class="col-sm-10">
                <div class="form-check rate">

                  <input type="radio" name="ratings" value="5" id="review_10" required>
                  <label for="review_10" title="5"></label>
                  
                  <input type="radio" name="ratings" value="4.5" id="review_9" required>
                  <label class="half" for="review_9" title="4.5"></label>

                  <input type="radio" name="ratings" value="4" id="review_8" required>
                  <label for="review_8" title="4"></label>
                  
                  <input type="radio" name="ratings" value="3.5" id="review_7" required>
                  <label class="half" for="review_7" title="3.5"></label>

                  <input type="radio" name="ratings" value="3" id="review_6" required>
                  <label for="review_6" title="3"></label>
                  
                  <input type="radio" name="ratings" value="2.5" id="review_5" required>
                  <label class="half" for="review_5" title="2.5"></label>

                  <input type="radio" name="ratings" value="2" id="review_4" required>
                  <label for="review_4" title="2"></label>
                  
                  <input type="radio" name="ratings" value="1.5" id="review_3" required>
                  <label class="half" for="review_3" title="1.5"></label>

                  <input type="radio" name="ratings" value="1" id="review_2" required>
                  <label for="review_2" title="1"></label>
                  
                  <input type="radio" name="ratings" value="0.5" id="review_1" required>
                  <label class="half" for="review_1" title="0.5"></label>
                  
                </div>
              </div>
            </div>

            <!-- Review Subject -->
            <div class="mb-3 row">
              <label for="subject" class="col-sm-2 col-form-label">Review Title</label>
              <div class="col-sm-10">
                <input type="text" name="subject" id="subject" class="form-control" >
              </div>
            </div>

            <!-- Review Body -->
            <div class="mb-3 row">
              <label for="review" class="col-sm-2 col-form-label">Review Body</label>
              <div class="col-sm-10">
                <textarea name="review" id="review" class="form-control"></textarea>
              </div>
            </div>


            <!-- If user is logged in then -->
            {% if user.is_authenticated %}
              <!-- if user ordered the product then -->
              {% if is_product_ordered %}
                <input type="submit" value="Submit Review" class="btn btn-primary">

              <!-- if user does not ordered the product then -->
              {% else %}
                <p>You must purchase {{ product.name }} to submit a review about it.
              {% endif %}

            <!-- if user is not logged in -->
            {% else %}
              <p>You must log in before posting your review. <span><a href="{% url 'login' %}">Login Now</a></span></p>
            {% endif %}

          </form>
        </article>
      </div>

      <div class="col-md-9">
        <header class="section-heading">
          <h3>Customer Reviews</h3>

          <!-- Showing average raing and total number of rating for this product -->
          <div class="rating-stars">
            <span>
              {# fa-star-o means blank star, fa-star-half-o means half star, fa-star means full star #}
              <i class="fa fa-star{% if product.average_rating < 0.5 %}-o{% elif product.average_rating < 1 %}-half-o {% endif %}"></i>
              <i class="fa fa-star{% if product.average_rating < 1.5 %}-o{% elif product.average_rating < 2 %}-half-o {% endif %}"></i>
              <i class="fa fa-star{% if product.average_rating < 2.5 %}-o{% elif product.average_rating < 3 %}-half-o {% endif %}"></i>
              <i class="fa fa-star{% if product.average_rating < 3.5 %}-o{% elif product.average_rating < 4 %}-half-o {% endif %}"></i>
              <i class="fa fa-star{% if product.average_rating < 4.5 %}-o{% elif product.average_rating < 5 %}-half-o {% endif %}"></i>
            </span>
            <span>Total {{ product.count_rating }} reviews</span>
          </div>
        </header>
        
        {% for review in reviews %}
          <article class="box mb-3">
            <div class="icontext w-100">
              <img
                src="{{ review.user_profile.profile_picture.url }}" alt="{{ review.user_profile }} profile picture"
                class="img-xs icon rounded-circle"
              />
              <div class="text">
                <span class="date text-muted float-md-right">{{ review.updated_at }} </span>
                <h6 class="mb-1">{{ review.user.full_name }}</h6>
                <div class="rating-stars">
                  <span>
                    {# fa-star-o means blank star, fa-star-half-o means half star, fa-star means full star #}
                    <i class="fa fa-star{% if review.ratings == 0.5 %}-half-o{% elif review.ratings < 1 %}-o {% endif %}"></i>
                    <i class="fa fa-star{% if review.ratings == 1.5 %}-half-o{% elif review.ratings < 2 %}-o {% endif %}"></i>
                    <i class="fa fa-star{% if review.ratings == 2.5 %}-half-o{% elif review.ratings < 3 %}-o {% endif %}"></i>
                    <i class="fa fa-star{% if review.ratings == 3.5 %}-half-o{% elif review.ratings < 4 %}-o {% endif %}"></i>
                    <i class="fa fa-star{% if review.ratings == 4.5 %}-half-o{% elif review.ratings < 5 %}-o {% endif %}"></i>
                  </span>
                </div>
              </div>
            </div>
            <!-- icontext.// -->
            <div class="mt-3">
              <h6>{{ review.subject }}</h6>
              <p>{{ review.review }}</p>
            </div>
          </article>
        {% endfor %}
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}